{
 "title": "Carbon Flame Projects",
 "tags": [
  "flame",
  "data"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "carbon flame projects at a glance",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(carbon_flame_projects * 0) + on(projectname,instance) group_left(archive_exists) carbon_flame_archives",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project size by number of frames",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(carbon_flame_projects) by (projectname,projectserver)",
     "legendFormat": "{{projectname}}"
    }
   ]
  },
  {
   "title": "Project archive size in GB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(carbon_flame_archives) by (projectname,projectserver) / 1024 / 1024 /1024",
     "legendFormat": "{{projectname}}"
    }
   ]
  }
 ]
}