{
 "title": "Carbon Projects",
 "tags": [
  "flame",
  "data",
  "vfx",
  "weka",
  "cg"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "carbon flame projects at a glance",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "carbon_flame_projects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Project size by number of frames",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(carbon_flame_projects) by (projectname,projectserver)",
     "legendFormat": "{{projectname}}"
    }
   ]
  },
  {
   "title": "Project archive size in GB",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "carbon_flame_archives / 1024 / 1024 /1024",
     "legendFormat": "{{projectname}}"
    }
   ]
  },
  {
   "title": "/vfx Project size in GB",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(carbon_vfx_projects) by (projectname) / 1024 / 1024",
     "legendFormat": "{{projectname}}"
    }
   ]
  }
 ]
}