{
 "title": "Carbon Ansible",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Play timing",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/ansible.log\"}\n|= \"Playbook run took\"\n| pattern \"<date> p=<pid> u=<user> n=<name> | <msg>\""
    }
   ]
  },
  {
   "title": "active ansible hosts by last apply time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by(hostname) (rate({filename=\"/var/log/ansible.log\"} |= `Playbook run took` | logfmt [$__interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "average play runtime in seconds by hostname",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg_over_time({filename=\"/var/log/ansible.log\"} \n|= `Playbook run took` \n| pattern `<preamble> | <msg> <days_int> days, <hours_int> hours, <mins_int> minutes, <sec_int> seconds`\n| unwrap sec_int [$__interval]) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}