{
 "title": "FLEXlm",
 "description": "FLEXlm License Manager `lmstat` license information.",
 "tags": [
  "prometheus",
  "flexlm"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(flexlm_server_status, app)"
    }
   },
   {
    "name": "feature",
    "label": "Feature",
    "query": {
     "query": "label_values(flexlm_feature_used{app=\"[[app]]\"}, name)"
    }
   },
   {
    "name": "lmstat_version",
    "query": {
     "query": "label_values(flexlm_lmstat_info, version)"
    }
   },
   {
    "name": "lmstat_arch",
    "query": {
     "query": "label_values(flexlm_lmstat_info, arch)"
    }
   },
   {
    "name": "lmstat_build",
    "query": {
     "query": "label_values(flexlm_lmstat_info, build)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(flexlm_exporter_build_info, version)"
    }
   },
   {
    "name": "branch",
    "query": {
     "query": "label_values(flexlm_exporter_build_info, branch)"
    }
   },
   {
    "name": "goversion",
    "query": {
     "query": "label_values(flexlm_exporter_build_info, goversion)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Licenses Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(flexlm_server_status{app=\"[[app]]\"})"
    }
   ]
  },
  {
   "title": "Server status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Status" }
   ],
   "targets": [
    {
     "expr": "flexlm_server_status{app=\"[[app]]\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Server status (now)",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "flexlm_server_status{app=\"[[app]]\"}"
    }
   ]
  },
  {
   "title": "Vendor status (now)",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "flexlm_vendor_status{app=\"[[app]]\"}"
    }
   ]
  },
  {
   "title": "\"[[app]]\" features expiration date",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flexlm_feature_expiration_seconds{app=\"[[app]]\"} * 1000"
    }
   ]
  },
  {
   "title": "Feature usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "feature",
   "targets": [
    {}
   ]
  },
  {
   "title": "\"[[feature]]\" usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flexlm_feature_used{app=\"[[app]]\", name=\"[[feature]]\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "flexlm_feature_issued{app=\"[[app]]\", name=\"[[feature]]\"}",
     "legendFormat": "max available"
    },
    {
     "expr": "sum(flexlm_feature_reserved_groups{app=\"[[app]]\", name=\"[[feature]]\"})",
     "legendFormat": "reserved"
    }
   ]
  },
  {
   "title": "\"[[feature]]\" usage by user (now)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flexlm_feature_used_users{app=\"[[app]]\",name=\"[[feature]]\"}) by (user)",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "\"[[feature]]\" reservation by group (now)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flexlm_feature_reserved_groups{app=\"[[app]]\",name=\"[[feature]]\"}) by (group)",
     "legendFormat": "{{ group }}"
    }
   ]
  }
 ]
}