{
 "title": "Projects Launched",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "flame projects launched today",
   "type": "table",
   "gridPos": { "h": 19, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (projectname) (sum_over_time(carbon_up{dcc=\"flame\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nuke projects launched today",
   "type": "table",
   "gridPos": { "h": 19, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "count by (projectname) (sum_over_time(carbon_up{dcc=\"nuke\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "maya projects launched today",
   "type": "table",
   "gridPos": { "h": 19, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count by (projectname) (sum_over_time(carbon_up{dcc=\"maya\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "flame projects launched today",
   "type": "table",
   "gridPos": { "h": 19, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (projectname) (sum_over_time(carbon_up{dcc=\"houdini\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}