{
 "title": "Weka NFS Statistics",
 "tags": [ "#weka" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "weka_datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(weka_info,cluster)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=/public/img/weka/WekaColor.svg>"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total NFS ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (weka_stats{cluster=\"$cluster\",category=\"ops_nfs\",stat=\"OPS\"})",
     "legendFormat": "NFS ops"
    }
   ]
  },
  {
   "title": "Total NFS Read Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (weka_stats{cluster=\"$cluster\",category=\"ops_nfs\",stat=\"READ_BYTES\"})",
     "legendFormat": "NFS ops"
    }
   ]
  },
  {
   "title": "NFS Reads vs Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum (weka_stats{cluster=\"$cluster\",category=\"ops_nfs\",stat=\"READS\"})",
     "legendFormat": "NFS Reads"
    },
    {
     "expr": "sum (weka_stats{cluster=\"$cluster\",category=\"ops_nfs\",stat=\"WRITES\"})",
     "legendFormat": "NFS Writes"
    }
   ]
  },
  {
   "title": "Total NFS Write Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (weka_stats{cluster=\"$cluster\",category=\"ops_nfs\",stat=\"WRITE_BYTES\"})",
     "legendFormat": "NFS ops"
    }
   ]
  },
  {
   "title": "io blocksize distribution heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (le) (weka_blocksize_bucket{cluster=\"$cluster\",category=\"ops_nfs\",stat=\"READ_SIZES\"})",
     "legendFormat": "{{le}} reads"
    },
    {
     "expr": "sum by (le) (weka_blocksize_bucket{cluster=\"$cluster\",category=\"ops_nfs\",stat=\"WRITE_SIZES\"})",
     "legendFormat": "{{le}} writes"
    }
   ]
  },
  {
   "title": "io blocksize distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (weka_blocksize_bucket{cluster=\"$cluster\",category=\"ops_nfs\",stat=\"READ_SIZES\"})",
     "legendFormat": "{{le}} reads"
    },
    {
     "expr": "sum by (le) (weka_blocksize_bucket{cluster=\"$cluster\",category=\"ops_nfs\",stat=\"WRITE_SIZES\"})",
     "legendFormat": "{{le}} writes"
    }
   ]
  }
 ]
}