{
 "title": "Weka Cluster Overview",
 "tags": [ "#weka" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "weka_datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(weka_info,cluster)"
    }
   },
   {
    "name": "gui_host",
    "query": {
     "query": "label_values(weka_stats{cluster=\"$cluster\",host_role=\"server\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=/public/img/weka/WekaColor.svg>"
   }
  },
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "weka_info{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_info{cluster=\"$cluster\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_info{cluster=\"$cluster\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "License Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_info{cluster=\"$cluster\"}",
     "legendFormat": "{{license_status}}"
    }
   ]
  },
  {
   "title": "IO Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_info{cluster=\"$cluster\"}",
     "legendFormat": "{{io_status}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_uptime{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Link Layer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_info{cluster=\"$cluster\"}",
     "legendFormat": "{{link_layer}}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "weka_num_servers_total{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Offline Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "weka_num_servers_total{cluster=\"$cluster\"} - weka_num_servers_active{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "stat",
   "description": "Total capacity of the cluster",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_drive_storage_total_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Unprovisioned",
   "type": "stat",
   "description": "Capacity that has not been put into a filesystem",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_drive_storage_unprovisioned_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(weka_alerts{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Used Capacity",
   "type": "graph",
   "description": "Total Used drive capacity",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "weka_drive_storage_total_bytes{cluster=\"$cluster\"} - weka_drive_storage_unprovisioned_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}} - allocated"
    },
    {
     "expr": "weka_drive_storage_total_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}} - total"
    }
   ]
  },
  {
   "title": "Current Throughput",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_overview_activity_write_bytespersec{cluster=\"$cluster\"}+weka_overview_activity_read_bytespersec{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Avg Throughput",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_overview_activity_write_bytespersec{cluster=\"$cluster\"}+weka_overview_activity_read_bytespersec{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Protection Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_protection{cluster=\"$cluster\"}",
     "legendFormat": "{{numFailures}} Failures"
    }
   ]
  },
  { "title": "Cluster Filesystem Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "FS Capacity Utilization %",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(weka_fs{cluster=\"$cluster\", stat=\"total_percent_used\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS SSD Utilization %",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(weka_fs{cluster=\"$cluster\", stat=\"ssd_percent_used\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS Total Used Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "weka_fs{cluster=\"$cluster\",stat=\"used_total\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS SSD Used Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "weka_fs{cluster=\"$cluster\",stat=\"used_ssd\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS Capacity Utilization %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "weka_fs{cluster=\"$cluster\", stat=\"total_percent_used\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS SSD Capacity Utilization %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "weka_fs{cluster=\"$cluster\", stat=\"ssd_percent_used\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS Total Used Capacity % Prediction next 30 days based on prev 30 days",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "abs(predict_linear(weka_fs{cluster=\"$cluster\",stat=\"total_percent_used\"}[30d], 86400*30)) < 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS SSD Used Capacity % Prediction next 30 days based on prev 30 days",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "abs(predict_linear(weka_fs{cluster=\"$cluster\",stat=\"ssd_percent_used\"}[30d], 86400*30)) < 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Cluster CPU Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Weka FE Core Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_stats{cluster=\"$cluster\",stat=\"CPU_UTILIZATION\",node_role=\"FRONTEND\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Weka Compute Core Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_stats{cluster=\"$cluster\",stat=\"CPU_UTILIZATION\",node_role=\"COMPUTE\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Weka Drives Core Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_stats{cluster=\"$cluster\",stat=\"CPU_UTILIZATION\",node_role=\"DRIVES\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  { "title": "Cluster-wide IO Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Operations per second, total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_ops{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Throughput per second, total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_read_bytespersec{cluster=\"$cluster\"} + weka_overview_activity_write_bytespersec{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Read vs Write IOPS, total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_write_iops{cluster=\"$cluster\"}",
     "legendFormat": "writes"
    },
    {
     "expr": "weka_overview_activity_read_iops{cluster=\"$cluster\"}",
     "legendFormat": "reads"
    }
   ]
  },
  {
   "title": "Read vs Write Bytes per second, total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_read_bytespersec{cluster=\"$cluster\"}",
     "legendFormat": "reads"
    },
    {
     "expr": "weka_overview_activity_write_bytespersec{cluster=\"$cluster\"}",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Metadata, total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_ops{cluster=\"$cluster\"} - weka_overview_activity_write_iops{cluster=\"$cluster\"} - weka_overview_activity_read_iops{cluster=\"$cluster\"}",
     "legendFormat": "metadata ops"
    }
   ]
  },
  {
   "title": "Download vs Upload Object Store Data Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "weka_overview_activity_object_download_bytespersec{cluster=\"$cluster\"}",
     "legendFormat": "download"
    },
    {
     "expr": "weka_overview_activity_object_upload_bytespersec{cluster=\"$cluster\"}",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Metadata by operation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"FILEOPEN_OPS\"})",
     "legendFormat": "open"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"CREATE_OPS\"})",
     "legendFormat": "create"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"FILECLOSE_OPS\"})",
     "legendFormat": "close"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"MKDIR_OPS\"})"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"READDIR_OPS\"})",
     "legendFormat": "read dir"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"REMOVE_OPS\"})",
     "legendFormat": "remove"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"RMDIR_OPS\"})",
     "legendFormat": "rmdir"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"UNLINK_OPS\"})",
     "legendFormat": "unlink"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"ACCESS_OPS\"})",
     "legendFormat": "access"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"COMMIT_OPS\"})"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"FLOCK_OPS\"})",
     "legendFormat": "flock"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"FSINFO_OPS\"})",
     "legendFormat": "fsinfo"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"GETATTR_OPS\"})",
     "legendFormat": "getattr"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"LINK_OPS\"})",
     "legendFormat": "link"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"MKNOD_OPS\"})",
     "legendFormat": "mknod"
    },
    {
     "expr": "sum(weka_stats{cluster=\"$cluster\",stat=\"RENAME_OPS\"})",
     "legendFormat": "rename"
    }
   ]
  },
  {
   "title": "io blocksize distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (weka_blocksize_bucket{cluster=\"$cluster\",category=\"ops_driver\",stat=\"READ_SIZES\"})",
     "legendFormat": "{{le}} reads"
    },
    {
     "expr": "sum by (le) (weka_blocksize_bucket{cluster=\"$cluster\",category=\"ops_driver\",stat=\"WRITE_SIZES\"})",
     "legendFormat": "{{le}} writes"
    }
   ]
  },
  {
   "title": "io blocksize distribution heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum by (le) (weka_blocksize_bucket{cluster=\"$cluster\",category=\"ops_driver\",stat=\"READ_SIZES\"})",
     "legendFormat": "{{le}} reads"
    },
    {
     "expr": "sum by (le) (weka_blocksize_bucket{cluster=\"$cluster\",category=\"ops_driver\",stat=\"WRITE_SIZES\"})",
     "legendFormat": "{{le}} writes"
    }
   ]
  },
  {
   "title": "io blocksize distribution (instant)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (weka_blocksize_bucket{cluster=\"$cluster\",category=\"ops_driver\",stat=\"READ_SIZES\"})",
     "legendFormat": "{{le}} reads"
    },
    {
     "expr": "sum by (le) (weka_blocksize_bucket{cluster=\"$cluster\",category=\"ops_driver\",stat=\"WRITE_SIZES\"})",
     "legendFormat": "{{le}} writes"
    }
   ]
  },
  { "title": "Cluster IO Statistcs by Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Operations per second by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"OPS\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Total Throughput per second by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"THROUGHPUT\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Reads per second by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"READS\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Read Bytes per second by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"READ_BYTES\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Writes per second by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"WRITES\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Write Bytes per second by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"WRITE_BYTES\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Metadata ops by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name) ( weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"OPS\"} ) - sum by (host_name)( weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"READS\"} )- sum by (host_name)( weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"WRITES\"} )",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Total IO Latency by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"READ_LATENCY\"})",
     "legendFormat": "{{host_name}} read"
    },
    {
     "expr": "avg by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"WRITE_LATENCY\"})",
     "legendFormat": "{{host_name}} write"
    }
   ]
  },
  { "title": "Top Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Top 5 Clients by IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"READS\",host_role=\"client\"}) + sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"WRITES\",host_role=\"client\"}))  ",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"THROUGHPUT\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by read iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"READS\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by read bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"READ_BYTES\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by write iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"WRITES\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by write bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"WRITE_BYTES\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"READ_LATENCY\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"WRITE_LATENCY\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients by Metadata Ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"OPS\",host_role=\"client\"}) - sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"READS\",host_role=\"client\"}) - sum by (host_name) (weka_stats{cluster=\"$cluster\",category=\"ops\",stat=\"WRITES\",host_role=\"client\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "per core stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization by NodeId/Core",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "weka_stats{cluster=\"$cluster\",category=\"cpu\",stat=\"CPU_UTILIZATION\"}",
       "legendFormat": "{{node_id}} {{host_name}} {{node_role}}"
      }
     ]
    }
   ]
  }
 ]
}