{
 "title": "Weka Filesystems Detail",
 "description": "Weka Server/Client Details",
 "tags": [ "#weka" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "weka_datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(weka_info,cluster)"
    }
   },
   {
    "name": "Filesystem",
    "query": {
     "query": "label_values(weka_fs{cluster=\"$cluster\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=/public/img/weka/WekaColor.svg>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Filesystem Flash Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 5 Filesystems by % SSD Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk( 5, weka_fs{cluster=\"$cluster\", stat=\"ssd_percent_used\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$Filesystem SSD Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "weka_fs{cluster=\"$cluster\", name=\"$Filesystem\", stat=\"ssd_percent_used\"}",
     "legendFormat": "SSD Used %"
    }
   ]
  },
  {
   "title": "$Filesystem SSD Occupancy",
   "type": "graph",
   "description": "SSD occupancy",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "weka_fs{cluster=\"$cluster\", name=\"$Filesystem\", stat=\"used_ssd\"}",
     "legendFormat": "SSD Used"
    },
    {
     "expr": "weka_fs{cluster=\"$cluster\", name=\"$Filesystem\", stat=\"available_ssd\"}",
     "legendFormat": "SSD Available"
    }
   ]
  },
  {
   "title": "$Filesystem Projected SSD % Use",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(predict_linear(weka_fs{cluster=\"$cluster\",name=\"$Filesystem\",stat=\"ssd_percent_used\"}[7d], 86400*30)) < 100",
     "legendFormat": "30-day future"
    },
    {
     "expr": "abs(predict_linear(weka_fs{cluster=\"$cluster\",name=\"$Filesystem\",stat=\"ssd_percent_used\"}[7d], 86400*7)) < 100",
     "legendFormat": "7-day future"
    },
    {
     "expr": "abs(predict_linear(weka_fs{cluster=\"$cluster\",name=\"$Filesystem\",stat=\"ssd_percent_used\"}[7d], 86400)) < 100",
     "legendFormat": "1-day future"
    },
    {
     "expr": "weka_fs{cluster=\"$cluster\",name=\"$Filesystem\",stat=\"ssd_percent_used\"}",
     "legendFormat": "Actual SSD Use %"
    }
   ]
  },
  {
   "title": "Total Capacity (Flash + Object)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 5 Filesystems by % Full (total capacity)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, weka_fs{cluster=\"$cluster\",stat=\"total_percent_used\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}