{
 "title": "Weka Metrics Exporter Stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "weka_datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Process Cpu Seconds",
   "type": "graph",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident memory bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Elapsed time to collect all stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "weka_collect_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Elapsed time to collect individual clusters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "weka_gather_seconds", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "Prometheus scrape duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "ave time per api call",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "weka_collect_timepercall", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "number of api calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "weka_collect_apicalls", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}